### ISSUE TITLE
something wrong with the CMakeLists.txt 

### ISSUE THREAD

**Issue by CharlieV5** [chengwei0427/ct-lio#1]
Maybe you haven't add the full codes of CMakeLists.txt, because it says the g2o libraries are not found.
<img width="850" alt="20230718163412" src="https://github.com/chengwei0427/ct-lio/assets/8245892/aa845d9f-7270-4264-bc9b-0cdfb392c455">

**Comment by chengwei0427** [comment]
Hi， @CharlieV5 
Thanks for your interesting in our project.
Before compile the code ,you should change the dependency library directory correctly. 
The  dependency library config is here:  **./cmake/packages.cmake**.

**Comment by CharlieV5** [comment]
OK, I see. Thank you!

**Comment by LIYVang** [comment]
抱歉，我也遇到了相同的问题，具体该怎么操作解决呢？
