### ISSUE TITLE
packages.cmake 下 依赖库很多作者本机环境的路径，无法完成编译

### ISSUE THREAD

**Issue by jiawenquan** [chengwei0427/ct-lio#11]

**Comment by chengwei0427** [comment]
需要你根据自己的环境，进行依赖调整的。

**Comment by zhh2005757** [comment]
确实，很多库作者直接引用但是并没有在仓库里提供，github也没有说明

**Comment by chengwei0427** [comment]
抱歉，当时上传时，直接按我的依赖就上传了！
这里很多都是Ubuntu18.04默认的依赖库，只需要**apt-get install** 即可，只有g2o和ceres需要你自己编译；

我最近在忙着做其他的project，依赖库安装，如果各位有整理好的，能运行通过的，也**欢迎提交PR**哈！
