### ISSUE TITLE
Can this CT-LIO integrate global location information？

### ISSUE THREAD

**Issue by Joosoo1** [chengwei0427/ct-lio#12]
Thank you very much for open-sourcing this job. I have recently planned to apply CT-LIO in my project to improve efficiently localization for unmanned vehicles in a very large environment, but usually, the localization becomes less accurate with the accumulation of time and distance. So we are planning to incorporate the position information provided by GPS into the SLAM system in the hope of improving the positioning accuracy， how should we incorporate the GPS information, please give us some suggestions!

**Comment by chengwei0427** [comment]
Hi, @Joosoo1 
Thanks for your interesting in our project.
CT-LIO is an odometry pipeline, and as such, we don't support incorporate  gps information now. Nevertheless, you can use the PGO as back-end to incorporate  the GPS, but you would have to modify the source code quite a bit.

For to moment, we don't plan to implement such functionality. Thanks for your interest in the project.

**Comment by Joosoo1** [comment]
Okay, thanks for the reply.
