### ISSUE TITLE
IMU Lidar Sync Issue

### ISSUE THREAD

**Issue by satyajitghana** [chengwei0427/ct-lio#14]
What does this mean?

"Please make sure the IMU and LiDAR are Synchronized, that's important."

If there's an inbuilt IMU, it should be synced right?

In the case of Robosense, there's no internal IMU, so which IMU did you use? and how do i synchronize the imu?

**Comment by chengwei0427** [comment]
Hi， @satyajitghana 
Thanks for your interesting in our work.
Based on loose coupling mechanism, our project  works very well on devices(lidar-imu) that are not time-synchronized.

**Comment by aditdoshi333** [comment]
@chengwei0427 Thanks for sharing amazing work. 

I tried ct lio on the Robosense staircase data which you shared. Can you please share which IMU you used? And also is it possible for you to share the complete dataset? As of now only 3 bag files are there.

**Comment by chengwei0427** [comment]
Hi, @aditdoshi333 
Thanks for your interesting in our work.
The **staircase data** is provided by the author of **PV_LIO**, I don't know the imu model.
More test data, you can refer to **Hilti2022 dataset, ICCV2023 challenge dataset, NCLT, M2DGR, UrbanLoco, lio-sam dataset, fastlio dataset** and so on.

**Comment by satyajitghana** [comment]
thanks for your input :)
