### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by goldtimes** [chengwei0427/ct-lio#17]
我使用自己的robosene数据包时发现，里程计部分似乎很耗时间。最后在终端上的打印显示播放包的速度为0.4x了。这个大佬有出现这样的情况么？

**Comment by chengwei0427** [comment]
你好， @goldtimes 
感谢关注我们的工作；
使用CT模式，确实会比较费时，你可以尝试修改为普通模式，运行一下看看，效率会提升很多。
