### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by sdwyc** [chengwei0427/ct-lio#3]
Hi, Looks like a nice work! I meet some problems during building! Do you display all dependencies in Readme.md? But, I have encountered many dependencies error, like g2o. Now I have install all lacked dependencies, but still have some error. contents as following:

-- Could NOT find DSSDK (missing: _DSSDK_LIBRARIES) 
** WARNING ** io features related to dssdk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

Can you give some useful suggestion for building?

**Comment by CharlieV5** [comment]
I guess you should manually change the thirdparty path in cmake file, as the author says in the README

**Comment by chengwei0427** [comment]
> I guess you should manually change the thirdparty path in cmake file, as the author says in the README

Hi, @sdwyc 

Thanks for interesting in our work!

Some third-party configurations are in the **cmake** file, I suggest you read the **_readme_** before test the program.
