### ISSUE TITLE
something about the precision

### ISSUE THREAD

**Issue by CharlieV5** [chengwei0427/ct-lio#4]
Hi, dear author! I see you post the comparison with PV-LIO, testing on staircase_crazy_rotation dataset. Looks very impressive!
Have you check the precision of the map you build and compare with PV-LIO, such as the thickness of the wall ? As I tested your program with this data, I found it seems that there is some twist of the stairways. Should I change some parameters in config file or the source code? Can I share your parameters?

**Comment by chengwei0427** [comment]
Hi, @CharlieV5 
Thabnks for your interesting in our work.
As mentioned in #2 and Readme, you should make sure your params is right. In addition, the staircase dataset's scan headerstamp is the frame end, you should uncomment the line in the main function before test this dataset.

**Comment by CharlieV5** [comment]
> Hi, @CharlieV5 Thanks for your interesting in our work. As mentioned in #2 and Readme, you should make sure your params is right. In addition, the staircase dataset's scan headerstamp is the frame end, you should uncomment the [line ](https://github.com/chengwei0427/ct-lio/blob/a05af59c032ff08df6905b06d2776a753d187741/src/apps/main_eskf.cpp#L60)in the main function before test this dataset.
> 
> For more instructions, I recommend you read **readme** again.

Thank you very much! I will do some other tests later.

**Comment by narutojxl** [comment]
I'm also interested in quantitative comparison with [PV-LIO](https://github.com/HViktorTsoi/PV-LIO) and [semi_elastic_lio](https://github.com/ZikangYuan/semi_elastic_lio).

**Comment by chengwei0427** [comment]
Hi, @narutojxl @CharlieV5 
Thanks for interesting in our work!
This project is just my personal experimental demonstration, no quantitative comparison test was performed with other methods. 
But any experimental feedback is welcome, and  I 'm happy to assist you with any queries or concerns you may have.

**Comment by CharlieV5** [comment]
Hello, @chengwei0427 
Do you estimate the extrinsic parameters of IMU to LiDAR? I see the "extrinsic_est_en" in mapping.yaml, but I don't see it is used. So this program demands the accuracy extrinsic parameters ？

**Comment by chengwei0427** [comment]
Hi， @CharlieV5 
This project does not estimate the extrinsic parameters, and the param file is just copied from 'fast-lio', the 'extrinsic_est_en' item was not deleted when upload.

In addition, due to the loose coupling mode, rough extrinsic parameters also work well .

Finally, do you have any test results? Any experimental feedback is welcome.

**Comment by CharlieV5** [comment]
> Hi， @CharlieV5 This project does not estimate the extrinsic parameters, and the param file is just copied from 'fast-lio', the 'extrinsic_est_en' item was not deleted when upload.
> 
> In addition, due to the loose coupling mode, rough extrinsic parameters also work well .
> 
> Finally, do you have any test results? Any experimental feedback is welcome.

Thank you. Maybe later, I will upload the test results.
