### ISSUE TITLE
It works for AVAI?

### ISSUE THREAD

**Issue by PeaceLove0811** [chengwei0427/ct-lio#7]
Hi, dear author. The CT-LIO has shown excellent performance on mechanical lidar. Whether the algorithm can be applied to avia or mid360? I notice that some codes like `AVIAHandler` are commented. If I uncomment these codes, can it work for avia? And in `AVIAHandler()`, some fields like `alpha_time relative_time` ,ect. are lack. I think they should be added into the `point_temp`. 
Last, I tryed all these steps, but it still doesn't work. I found that in
 `zjloc::RosbagIO rosbag_io(bag_path_);
 rosbag_io.AddPointCloud2Handle()`
Whether it firstlt load the rosbag into memory, then run. So need I add the `AddCustomPointCloudHandle()` in `RosbagIO`?
Thanks a lot!

**Comment by chengwei0427** [comment]
Hi,  @PeaceLove0811 
Thanks for interesting in our work!
The CT_LIO does not support avia or mid360 currently. But it is **easy to extend** to these devices.
You just need to complete these parts of the code change in **cloud_convert**, I think it's easy for you.

**Comment by PeaceLove0811** [comment]
>@chengwei0427 

Thanks for your reply! 
I have tryed, but in this scope:
```
void CloudConvert::Process(const livox_ros_driver::CustomMsg::ConstPtr &msg, FullCloudPtr &pcl_out)`
{
       AviaHandler(msg);
       *pcl_out = cloud_out_;
}
```
Need I change the `FullCloudPtr` to `std::vector<point3D>`? 
Because the datastruct `FullPointType` does not contain `relative_time alpha_time` fields
And I made some change in `AviaHandler` here：
```
 void CloudConvert::Process(const livox_ros_driver::CustomMsg::ConstPtr &msg, std::vector<point3D> &pcl_out)
    {
        AviaHandler(msg);
    }

 void CloudConvert::AviaHandler(const livox_ros_driver::CustomMsg::ConstPtr &msg)
    {
        cout << "Come in AviaHandler" << endl;
        cloud_out_.clear();
        cloud_full_.clear();
        int plsize = msg->point_num;

        cloud_out_.reserve(plsize);
        cloud_full_.resize(plsize);

        std::vector<bool> is_valid_pt(plsize, false);
        std::vector<uint> index(plsize - 1);
        for (uint i = 0; i < plsize - 1; ++i)
        {
            index[i] = i + 1; // 从1开始
        }

        timespan_ = msg->points.back().offset_time / float(1000000);

        for (int i = 0; i < plsize; i++)
        {
            if ((msg->points[i].line < num_scans_) &&
                ((msg->points[i].tag & 0x30) == 0x10 || (msg->points[i].tag & 0x30) == 0x00)) {
                if (i % point_filter_num_ == 0)
                {
                    point3D point_temp;
                    point_temp.raw_point = Eigen::Vector3d(msg->points[i].x, msg->points[i].y, msg->points[i].z);
                    point_temp.point = point_temp.raw_point;
                    point_temp.relative_time = msg->points[i].offset_time / float(1000000);
                    point_temp.intensity = msg->points[i].reflectivity;
                    point_temp.timestamp = point_temp.relative_time + msg->timebase;
                    point_temp.alpha_time = point_temp.relative_time / timespan_;
                    point_temp.timespan = timespan_;
                    point_temp.ring = msg->points[i].line;
                    if (point_temp.alpha_time > 1 || point_temp.alpha_time < 0)
                        std::cout << point_temp.alpha_time << ", this may error." << std::endl;

                    cloud_out_.push_back(point_temp);
                }
            }
        };
    }
```

**Comment by chengwei0427** [comment]
Hi, @PeaceLove0811 

It looks roughly right, but it needs to be adjusted for your data type.
Good luck!

**Comment by chengwei0427** [comment]
Hi, @PeaceLove0811 
Livox serials LiDAR is adapted  currently.
